--liquibase formatted sql

--changeset igor:1
CREATE TABLE IF NOT EXISTS add_pay
(
    id              INT8 GENERATED BY DEFAULT AS IDENTITY,
    add_pay_code    VARCHAR(255) NOT NULL,
    add_pay_name    VARCHAR(255) NOT NULL,
    description     VARCHAR(255),
    max_percent     int4         NOT NULL,
    add_pay_type_id INT8         NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:2
CREATE TABLE IF NOT EXISTS add_pay_fund
(
    id                       INT8 GENERATED BY DEFAULT AS IDENTITY,
    add_pay_funds            NUMERIC(19, 2) NOT NULL,
    number_order             VARCHAR(255)   NOT NULL,
    number_order_trade_union VARCHAR(255)   NOT NULL,
    add_pay_type_id          INT8           NOT NULL,
    calc_settings_id         INT8           NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:3
CREATE TABLE IF NOT EXISTS add_pay_result
(
    id             INT8 GENERATED BY DEFAULT AS IDENTITY,
    percent        float8         NOT NULL,
    sum            NUMERIC(19, 2) NOT NULL,
    add_pay_id     INT8           NOT NULL,
    basic_norms_id INT8           NOT NULL,
    time_sheet_id  INT8           NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:4
CREATE TABLE IF NOT EXISTS add_pay_type
(
    id                INT8 GENERATED BY DEFAULT AS IDENTITY,
    add_pay_type_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:5
CREATE TABLE IF NOT EXISTS basic_norms
(
    id               INT8 GENERATED BY DEFAULT AS IDENTITY,
    basic_norm_date  date           NOT NULL,
    basic_norm_name  VARCHAR(255)   NOT NULL,
    basic_norm_value NUMERIC(19, 2) NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:6
CREATE TABLE IF NOT EXISTS calc_settings
(
    id           INT8 GENERATED BY DEFAULT AS IDENTITY,
    calc_date    date NOT NULL,
    working_days int4 NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:7
CREATE TABLE IF NOT EXISTS people
(
    id               INT8 GENERATED BY DEFAULT AS IDENTITY,
    address          VARCHAR(255) NOT NULL,
    first_name       VARCHAR(255) NOT NULL,
    patronymic       VARCHAR(255) NOT NULL,
    personnel_number VARCHAR(255),
    phone_number     VARCHAR(255) NOT NULL,
    sur_name         VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:8
CREATE TABLE IF NOT EXISTS percent_salary
(
    id                               INT8 GENERATED BY DEFAULT AS IDENTITY,
    percent_salary_all               int4         NOT NULL,
    percent_salary_for_young_special int4         NOT NULL,
    percent_start_date               date         NOT NULL,
    percent_young_special_code       VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:9
CREATE TABLE IF NOT EXISTS percent_salary_result
(
    id                INT8 GENERATED BY DEFAULT AS IDENTITY,
    percent           int4           NOT NULL,
    sum               NUMERIC(19, 2) NOT NULL,
    percent_salary_id INT8           NOT NULL,
    time_sheet_id     INT8           NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:10
CREATE TABLE IF NOT EXISTS position
(
    id            INT8 GENERATED BY DEFAULT AS IDENTITY,
    position_name VARCHAR(255) NOT NULL,
    sorting       int4         NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:11
CREATE TABLE IF NOT EXISTS staff_list
(
    id            INT8 GENERATED BY DEFAULT AS IDENTITY,
    disabled      boolean default false,
    salary        NUMERIC(19, 2) NOT NULL,
    young_special boolean default false,
    people_id     INT8           NOT NULL,
    position_id   INT8           NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:12
CREATE TABLE IF NOT EXISTS time_sheet
(
    id                 INT8 GENERATED BY DEFAULT AS IDENTITY,
    actual_days_worked int4 NOT NULL,
    calc_settings_id   INT8 NOT NULL,
    staff_list_id      INT8 NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:13
CREATE TABLE IF NOT EXISTS users
(
    id        INT8 GENERATED BY DEFAULT AS IDENTITY,
    login     VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    role      VARCHAR(255) NOT NULL,
    people_id INT8         NOT NULL,
    PRIMARY KEY (id)
);